apiVersion: v1
kind: Pod
metadata:
  name: alpine1
  namespace: default
spec:
  containers:
  - image: alpine:3.3
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
